// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDC4h50FcESfOqAt10htFlTdB0XyLmHs',
    appId: '1:453891629595:web:d972ac92c1c2a51d6c0ebe',
    messagingSenderId: '453891629595',
    projectId: 'ai-integrated-app',
    authDomain: 'ai-integrated-app.firebaseapp.com',
    databaseURL: 'https://ai-integrated-app-default-rtdb.firebaseio.com',
    storageBucket: 'ai-integrated-app.appspot.com',
    measurementId: 'G-6LEYCMR6DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ai2QcXUW5hi-Ff85t1UIHO1Pwu9pmmE',
    appId: '1:453891629595:android:ba0631a0fd7ca5ee6c0ebe',
    messagingSenderId: '453891629595',
    projectId: 'ai-integrated-app',
    databaseURL: 'https://ai-integrated-app-default-rtdb.firebaseio.com',
    storageBucket: 'ai-integrated-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_GdfN0XuMPQ0DL3PWrycywKVbv8AJVo',
    appId: '1:453891629595:ios:ba88a21a4b4ce7866c0ebe',
    messagingSenderId: '453891629595',
    projectId: 'ai-integrated-app',
    databaseURL: 'https://ai-integrated-app-default-rtdb.firebaseio.com',
    storageBucket: 'ai-integrated-app.appspot.com',
    iosClientId: '453891629595-r36uv2m6ictoa1c1tsq6gvmpiovht03e.apps.googleusercontent.com',
    iosBundleId: 'com.khoatransoftware.bluetoothTestBeaconApp',
  );
}
